### GET /
GET http://localhost:5003/


###
POST http://localhost:5003/auth/register 
Content-Type: application/json

{
    "username": "user1@gmail.com",
    "password": "12345"
}

###
POST http://localhost:5003/auth/login 
Content-Type: application/json

{
    "username": "user1@gmail.com",
    "password": "12345"
}

// user@gmail.com 12345678